name: convert-and-upload

on:
  push:
    branches:
      - main

jobs:
  convert-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
          cache: pip
      - run: pip install -r requirements.txt
      - name: convert markdown to json and upload to elastic
        run: |
          python3 /home/runner/work/search-bitcoin/search-bitcoin/code/convert_to_json_upload_to_elastic.py ${{ steps.abc.outputs.added_modified }}
        env:
            BTCTRANSCRIPTS_PASSWORD: ${{ secrets.BTCTRANSCRIPTS_PASSWORD }}
            BTCTRANSCRIPTS_SERVER_URI: ${{ secrets.BTCTRANSCRIPTS_SERVER_URI }}
            BTCTRANSCRIPTS_USERNAME: ${{ secrets.BTCTRANSCRIPTS_USERNAME }}